romania = {
    "Alba": ["Alba Iulia", "Aiud", "Blaj", "Cugir", "Sebeș"],
    "Arad": ["Arad", "Ineu", "Lipova", "Pâncota", "Sântana"],
    "Argeș": ["Pitești", "Câmpulung", "Curtea de Argeș", "Mioveni", "Ștefănești"],
    "Bacău": ["Bacău", "Onești", "Buhuși", "Comănești", "Moinești"],
    "Bihor": ["Oradea", "Beiuș", "Marghita", "Salonta", "Ștei"],
    "Bistrița-Năsăud": ["Bistrița", "Beclean", "Năsăud", "Sângeorz-Băi"],
    "Botoșani": ["Botoșani", "Dorohoi", "Darabani", "Flămânzi", "Săveni"],
    "Brașov": ["Brașov", "Codlea", "Făgăraș", "Râșnov", "Săcele"],
    "Brăila": ["Brăila", "Făurei", "Ianca", "Însurăței"],
    "Buzău": ["Buzău", "Nehoiu", "Pătârlagele", "Pogoanele", "Râmnicu Sărat"],
    "Caraș-Severin": ["Reșița", "Anina", "Băile Herculane", "Bocșa", "Caransebeș"],
    "Călărași": ["Călărași", "Budești", "Fundulea", "Lehliu Gară", "Oltenița"],
    "Cluj": ["Cluj-Napoca", "Câmpia Turzii", "Dej", "Gherla", "Turda"],
    "Constanța": ["Constanța", "Eforie", "Mangalia", "Medgidia", "Năvodari"],
    "Covasna": ["Sfântu Gheorghe", "Baraolt", "Covasna", "Întorsura Buzăului", "Târgu Secuiesc"],
    "Dâmbovița": ["Târgoviște", "Fieni", "Găești", "Moreni", "Pucioasa"],
    "Dolj": ["Craiova", "Băilești", "Calafat", "Dăbuleni", "Filiași"],
    "Galați": ["Galați", "Berești", "Târgu Bujor"],
    "Giurgiu": ["Giurgiu", "Bolintin-Vale", "Mihăilești"],
    "Gorj": ["Târgu Jiu", "Bumbești-Jiu", "Motru", "Novaci", "Rovinari"],
    "Harghita": ["Miercurea Ciuc", "Bălan", "Borsec", "Gheorgheni", "Odorheiu Secuiesc"],
    "Hunedoara": ["Deva", "Brad", "Hunedoara", "Lupeni", "Orăștie", "Petroșani"],
    "Ialomița": ["Slobozia", "Amara", "Fetești", "Fierbinți-Târg", "Țăndărei", "Urziceni"],
    "Iași": ["Iași", "Hârlău", "Pașcani", "Podu Iloaiei", "Târgu Frumos"],
    "Ilfov": ["Buftea", "Bragadiru", "Măgurele", "Otopeni", "Voluntari"],
    "Maramureș": ["Baia Mare", "Borșa", "Cavnic", "Dragomirești", "Sighetu Marmației", "Târgu Lăpuș"],
    "Mehedinți": ["Drobeta-Turnu Severin", "Baia de Aramă", "Orșova", "Strehaia", "Vânju Mare"],
    "Mureș": ["Târgu Mureș", "Iernut", "Luduș", "Reghin", "Sighișoara", "Sovata", "Târnăveni"],
    "Neamț": ["Piatra Neamț", "Bicaz", "Roman", "Târgu Neamț"],
    "Olt": ["Slatina", "Balș", "Caracal", "Corabia", "Drăgănești-Olt", "Piatra-Olt", "Scornicești", "Potcoava"],
    "Prahova": ["Ploiești", "Azuga", "Băicoi", "Boldești-Scăeni", "Breaza", "Bușteni", "Comarnic", "Mizil", "Plopeni", "Sinaia", "Slănic", "Urlați", "Vălenii de Munte"],
    "Sălaj": ["Zalău", "Jibou", "Șimleu Silvaniei", "Cehu Silvaniei"],
    "Satu Mare": ["Satu Mare", "Ardud", "Carei", "Livada", "Negrești-Oaș", "Tășnad"],
    "Sibiu": ["Sibiu", "Agnita", "Avrig", "Cisnădie", "Copșa Mică", "Dumbrăveni", "Miercurea Sibiului", "Ocna Sibiului", "Săliște", "Tălmaciu"],
    "Suceava": ["Suceava", "Broșteni", "Cajvana", "Câmpulung Moldovenesc", "Dolhasca", "Fălticeni", "Frasin", "Gura Humorului", "Liteni", "Milișăuți", "Rădăuți", "Siret", "Solca", "Vatra Dornei", "Vicovu de Sus"],
    "Teleorman": ["Alexandria", "Roșiorii de Vede", "Turnu Măgurele", "Videle", "Zimnicea"],
    "Timiș": ["Timișoara", "Buziaș", "Ciacova", "Deta", "Făget", "Gătaia", "Jimbolia", "Lugoj", "Recaș", "Sânnicolau Mare"],
    "Tulcea": ["Tulcea", "Babadag", "Isaccea", "Măcin", "Sulina"],
    "Vaslui": ["Vaslui", "Bârlad", "Huși", "Murgeni", "Negrești"],
    "Vâlcea": ["Râmnicu Vâlcea", "Băbeni", "Băile Govora", "Băile Olănești", "Bălcești", "Berbești", "Brezoi", "Călimănești", "Horezu"],
    "Vrancea": ["Focșani", "Adjud", "Mărășești", "Odobești", "Panciu"],
    "București": ["București"]
}
